code_generator/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

app_name = 'code_generator'

urlpatterns = [
    path('index/', index, name="index"),
    path('logout/', logout, name="logout"),
    path('create_code/', create_code, name="create_code"),
    path('search_code/', search_code, name="search_code"),
    path('update_code/', update_code, name="update_code"),
    path('delete_code/', delete_code, name="delete_code"),
    path('create_code/<int:field_number>/', create_code, name="create_code"),
    path('search_code/<int:field_number>/', search_code, name="search_code"),
    path('update_code/<int:field_number>/', update_code, name="update_code"),
    path('delete_code/<int:field_number>/', delete_code, name="delete_code"),
    url('404/', handler404),
    url('500/', handler500),

]

config/urls.py
from django.contrib import admin
from django.urls import include, path
#from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('code_generator/', include('code_generator.urls')),
]

""" Take this comment out to enable DebugToolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
"""

code_generator/models.py
from django.db import models


# Create your models here.
class CodeGeneratorRouter:
    """
    A router to control all database operations on models in the
    user application.
    """

    def db_for_read(self, model, **hints):
        """
        Attempts to read user models go to users_db.
        """
        if model._meta.app_label == 'code_generator':
            return 'hsm_01'
        elif model._meta.app_label == 'django':
            return 'default'
        return None

    def db_for_write(self, model, **hints):
        """
        Attempts to write user models go to users_db.
        """
        if model._meta.app_label == 'code_generator':
            return 'hsm_01'
        elif model._meta.app_label == 'django':
            return 'default'
        return None

    def allow_relation(self, obj1, obj2, **hints):
        """
        Allow relations if a model in the user app is involved.
        """
        if obj1._meta.app_label == 'code_generator' or \
                obj2._meta.app_label == 'code_generator':
            return True
        return None

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        """
        Make sure the auth app only appears in the 'users_db'
        database.
        """
        if app_label == 'code_generator':
            return db == 'hsm_01'
        return None

code_generator/views.py
from django.shortcuts import render
from django.db import IntegrityError
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import auth
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.models import User
from django.db.models import Sum


# Create your views here.


def index(request):
    if request.method == 'GET':
        if request.user is not None and request.user.is_superuser:
            return render(request, 'code_generator/index.html')


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/code_generator/login/')


def create_code(request, field_number=0):
    if request.method == 'GET':
        if request.user is not None and request.user.is_superuser:
            if field_number == 0:
                return render(request, 'code_generator/create_code.html')
            else:
                pass


def search_code(request, field_number=0):
    if request.method == 'GET':
        if request.user is not None and request.user.is_superuser:
            if field_number == 0:
                return render(request, 'code_generator/search_code.html')
            else:
                pass


def update_code(request, field_number=0):
    if request.method == 'GET':
        if request.user is not None and request.user.is_superuser:
            if field_number == 0:
                return render(request, 'code_generator/update_code.html')
            else:
                pass


def delete_code(request, field_number=0):
    if request.method == 'GET':
        if request.user is not None and request.user.is_superuser:
            if field_number == 0:
                return render(request, 'code_generator/delete_code.html')
            else:
                pass


# 404 page ############################################################################################


def handler404(request, exception):
    response = render(request, 'code_generator/404.html')
    response.status_code = 404
    return response


def handler500(request):
    response = render(request, 'code_generator/404.html')
    response.status_code = 500
    return response

code_generator/templates/code_generator/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>code產生器-{% block title %} {% endblock %}</title>
  <!-- Custom fonts for this template-->
  <link href="{% static 'code_generator/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'code_generator/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'code_generator:index' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">程式碼產生器</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - 主頁 -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'code_generator:index' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>主頁</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        資料
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>新建程式碼</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">動作:</h6>
            <a class="collapse-item" href="{% url 'code_generator:create_code'%}">新增</a>
            <a class="collapse-item" href="{% url 'code_generator:search_code'%}">查詢</a>
            <a class="collapse-item" href="{% url 'code_generator:update_code'%}">修改</a>
            <a class="collapse-item" href="{% url 'code_generator:delete_code'%}">刪除</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>目前資料</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">資料:</h6>
            <a class="collapse-item" href="{% url 'code_generator:create_code'%}">新增</a>
            <a class="collapse-item" href="{% url 'code_generator:search_code'%}">查詢</a>
            <a class="collapse-item" href="{% url 'code_generator:update_code'%}">修改</a>
            <a class="collapse-item" href="{% url 'code_generator:delete_code'%}">刪除</a>
          </div>
        </div>
      </li>
      <!-- Divider -->

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
          <ul class="navbar-nav ml-auto">
            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user}}</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  登出
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        {% block content %} {% endblock %}

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">要離開了嗎?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">選擇"登出"將登出目前帳號</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">取消</button>
          <a class="btn btn-primary" href="{% url 'code_generator:logout' %}">登出</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'code_generator/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'code_generator/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'code_generator/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'code_generator/js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'code_generator/vendor/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'code_generator/js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'code_generator/js/demo/chart-pie-demo.js' %}"></script>
  {% block javascript %} {% endblock %}
</body>

</html>

code_generator/templates/code_generator/blank.html
{% extends "code_generator/base.html" %}
{% load static %}
{% block title %} blank {% endblock %}
{% block content %}
    <div class="container-fluid">

      <!-- Page Heading -->
      <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

    </div>
    <!-- /.container-fluid -->
{% endblock %}
{% block javascript %} {% endblock %}

code_generator/templates/code_generator/create_code.html
{% extends "code_generator/base.html" %}
{% load static %}
{% block title %} blank {% endblock %}
{% block content %}
    <div class="container-fluid">

      <!-- Page Heading -->
      <h5 class="mb-4 text-gray-800">SQL代碼: </h5>
      <form id="form">
          <input type="text" class="form-control col-12" value="" placeholder="請輸入:"/>
          <br>
          <input type="button" class="btn btn-info" onclick="addField();" value="增加欄位"/>
          <input type="button" class="btn btn-info" onclick="deleteField();" value="減少欄位"/>




      </form>
    </div>
    <!-- /.container-fluid -->
{% endblock %}
{% block javascript %}
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <script>
        var fieldNumber = 1;
        function addField(){
            fieldNumber++;
            console.log(fieldNumber);
        }
        function deleteField(){
            fieldNumber--;
            console.log(fieldNumber);
        }

    </script>
{% endblock %}

code_generator/templates/code_generator/delete_code.html
{% extends "code_generator/base.html" %}
{% load static %}
{% block title %} blank {% endblock %}
{% block content %}
    <div class="container-fluid">

      <!-- Page Heading -->
      <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

    </div>
    <!-- /.container-fluid -->
{% endblock %}
{% block javascript %}

{% endblock %}

code_generator/templates/code_generator/index.html
{% extends "code_generator/base.html" %}
{% load static %}
{% block title %} blank {% endblock %}
{% block content %}
    <div class="container-fluid">

      <!-- Page Heading -->
      <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

    </div>
    <!-- /.container-fluid -->
{% endblock %}
{% block javascript %}

{% endblock %}

code_generator/templates/code_generator/search_code.html
{% extends "code_generator/base.html" %}
{% load static %}
{% block title %} blank {% endblock %}
{% block content %}
    <div class="container-fluid">

      <!-- Page Heading -->
      <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

    </div>
    <!-- /.container-fluid -->
{% endblock %}
{% block javascript %}

{% endblock %}

code_generator/templates/code_generator/update_code.html
{% extends "code_generator/base.html" %}
{% load static %}
{% block title %} blank {% endblock %}
{% block content %}
    <div class="container-fluid">

      <!-- Page Heading -->
      <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

    </div>
    <!-- /.container-fluid -->
{% endblock %}
{% block javascript %}

{% endblock %}